package defpackage;

/* renamed from: l81  reason: default package */
public interface l81 {
    public static final o A;
    public static final o B;
    public static final o C;
    public static final o D;
    public static final o E;
    public static final o F;
    public static final o G;
    public static final o H;
    public static final o I;
    public static final o J;
    public static final o b;
    public static final o c;
    public static final o d;
    public static final o e;
    public static final o f;
    public static final o g;
    public static final o h;
    public static final o i;
    public static final o j;
    public static final o k;
    public static final o l;
    public static final o m;
    public static final o n;
    public static final o o;
    public static final o p;
    public static final o q;
    public static final o r;
    public static final o s;
    public static final o t;
    public static final o u;
    public static final o v;
    public static final o w;
    public static final o x;
    public static final o y;
    public static final o z;

    static {
        o oVar = new o("1.2.840.10045");
        o oVar2 = new o("1", oVar);
        b = new o("1", oVar2);
        o oVar3 = new o("2", oVar2);
        c = oVar3;
        oVar3.w("3.1");
        d = new o("3.2", oVar3);
        e = new o("3.3", oVar3);
        o oVar4 = new o("4", oVar);
        oVar4.w("1");
        f = new o("1", new o("2", oVar));
        o oVar5 = new o("3", oVar4);
        g = new o("1", oVar5);
        h = new o("2", oVar5);
        i = new o("3", oVar5);
        j = new o("4", oVar5);
        o oVar6 = new o("3", oVar);
        o oVar7 = new o("0", oVar6);
        k = new o("1", oVar7);
        l = new o("2", oVar7);
        m = new o("3", oVar7);
        n = new o("4", oVar7);
        o = new o("5", oVar7);
        p = new o("6", oVar7);
        q = new o("7", oVar7);
        oVar7.w("8");
        oVar7.w("9");
        r = new o("10", oVar7);
        s = new o("11", oVar7);
        t = new o("12", oVar7);
        u = new o("13", oVar7);
        oVar7.w("14");
        oVar7.w("15");
        v = new o("16", oVar7);
        w = new o("17", oVar7);
        x = new o("18", oVar7);
        y = new o("19", oVar7);
        z = new o("20", oVar7);
        o oVar8 = new o("1", oVar6);
        A = new o("1", oVar8);
        B = new o("2", oVar8);
        C = new o("3", oVar8);
        D = new o("4", oVar8);
        E = new o("5", oVar8);
        F = new o("6", oVar8);
        G = new o("7", oVar8);
        new o("1.2.840.10040.4.1");
        new o("1.2.840.10040.4.3");
        o oVar9 = new o("1.3.133.16.840.63.0");
        H = new o("2", oVar9);
        I = new o("3", oVar9);
        J = new o("16", oVar9);
        o oVar10 = new o("1.2.840.10046");
        oVar10.w("2.1");
        o oVar11 = new o("3", oVar10);
        oVar11.w("1");
        oVar11.w("2");
        oVar11.w("3");
        yg.d(oVar11, "4", "5", "6", "7");
        oVar11.w("8");
        o oVar12 = new o("1", new o("1.3.133.16.840.9.44"));
        oVar12.w("1");
        oVar12.w("2");
    }
}