package defpackage;

/* renamed from: qa2  reason: default package */
public final class qa2 {
    public static final da a;
    public static final da b;
    public static final da c;
    public static final da d;
    public static final da e;
    public static final da f;
    public static final da g;
    public static final da h;
    public static final da i;
    public static final da j;
    public static final da k;
    public static final da l;
    public static final da m;
    public static final da n;

    static {
        da daVar = new da();
        daVar.a = 3;
        daVar.b = "Google Play In-app Billing API version is less than 3";
        a = daVar;
        da daVar2 = new da();
        daVar2.a = 3;
        daVar2.b = "Google Play In-app Billing API version is less than 9";
        da daVar3 = new da();
        daVar3.a = 3;
        daVar3.b = "Billing service unavailable on device.";
        b = daVar3;
        da daVar4 = new da();
        daVar4.a = 5;
        daVar4.b = "Client is already in the process of connecting to billing service.";
        c = daVar4;
        da daVar5 = new da();
        daVar5.a = 5;
        daVar5.b = "The list of SKUs can't be empty.";
        da daVar6 = new da();
        daVar6.a = 5;
        daVar6.b = "SKU type can't be empty.";
        d = daVar6;
        da daVar7 = new da();
        daVar7.a = 5;
        daVar7.b = "Product type can't be empty.";
        e = daVar7;
        da daVar8 = new da();
        daVar8.a = -2;
        daVar8.b = "Client does not support extra params.";
        f = daVar8;
        da daVar9 = new da();
        daVar9.a = 5;
        daVar9.b = "Invalid purchase token.";
        da daVar10 = new da();
        daVar10.a = 6;
        daVar10.b = "An internal error occurred.";
        g = daVar10;
        da daVar11 = new da();
        daVar11.a = 5;
        daVar11.b = "SKU can't be null.";
        da daVar12 = new da();
        daVar12.a = 0;
        daVar12.b = "";
        h = daVar12;
        da daVar13 = new da();
        daVar13.a = -1;
        daVar13.b = "Service connection is disconnected.";
        i = daVar13;
        da daVar14 = new da();
        daVar14.a = -3;
        daVar14.b = "Timeout communicating with service.";
        j = daVar14;
        da daVar15 = new da();
        daVar15.a = -2;
        daVar15.b = "Client does not support subscriptions.";
        k = daVar15;
        da daVar16 = new da();
        daVar16.a = -2;
        daVar16.b = "Client does not support subscriptions update.";
        da daVar17 = new da();
        daVar17.a = -2;
        daVar17.b = "Client does not support get purchase history.";
        da daVar18 = new da();
        daVar18.a = -2;
        daVar18.b = "Client does not support price change confirmation.";
        da daVar19 = new da();
        daVar19.a = -2;
        daVar19.b = "Play Store version installed does not support cross selling products.";
        da daVar20 = new da();
        daVar20.a = -2;
        daVar20.b = "Client does not support multi-item purchases.";
        l = daVar20;
        da daVar21 = new da();
        daVar21.a = -2;
        daVar21.b = "Client does not support offer_id_token.";
        m = daVar21;
        da daVar22 = new da();
        daVar22.a = -2;
        daVar22.b = "Client does not support ProductDetails.";
        n = daVar22;
        da daVar23 = new da();
        daVar23.a = -2;
        daVar23.b = "Client does not support in-app messages.";
        da daVar24 = new da();
        daVar24.a = -2;
        daVar24.b = "Client does not support alternative billing.";
        da daVar25 = new da();
        daVar25.a = 5;
        daVar25.b = "Unknown feature";
        da daVar26 = new da();
        daVar26.a = -2;
        daVar26.b = "Play Store version installed does not support get billing config.";
        da daVar27 = new da();
        daVar27.a = -2;
        daVar27.b = "Query product details with serialized docid is not supported.";
    }
}