package defpackage;

/* renamed from: sm0  reason: default package */
public interface sm0 {
    public static final o A;
    public static final o B;
    public static final o C;
    public static final o D;
    public static final o E;
    public static final o F;
    public static final o G;
    public static final o H;
    public static final o I;
    public static final o J;
    public static final o K;
    public static final o L;
    public static final o M;
    public static final o N;
    public static final o O;
    public static final o P;
    public static final o Q;
    public static final o R;
    public static final o S;
    public static final o a;
    public static final o b;
    public static final o c;
    public static final o d;
    public static final o e;
    public static final o f;
    public static final o g;
    public static final o h;
    public static final o i;
    public static final o j;
    public static final o k;
    public static final o l;
    public static final o m;
    public static final o n;
    public static final o o;
    public static final o p;
    public static final o q;
    public static final o r;
    public static final o s;
    public static final o t;
    public static final o u;
    public static final o v;
    public static final o w;
    public static final o x;
    public static final o y;
    public static final o z;

    static {
        o oVar = new o("1.3.132.0");
        a = new o("1", oVar);
        b = new o("2", oVar);
        c = new o("3", oVar);
        d = new o("4", oVar);
        e = new o("5", oVar);
        f = new o("6", oVar);
        g = new o("7", oVar);
        h = new o("8", oVar);
        i = new o("9", oVar);
        j = new o("10", oVar);
        k = new o("15", oVar);
        l = new o("16", oVar);
        m = new o("17", oVar);
        n = new o("22", oVar);
        o = new o("23", oVar);
        p = new o("24", oVar);
        q = new o("25", oVar);
        r = new o("26", oVar);
        s = new o("27", oVar);
        t = new o("28", oVar);
        u = new o("29", oVar);
        v = new o("30", oVar);
        w = new o("31", oVar);
        x = new o("32", oVar);
        y = new o("33", oVar);
        z = new o("34", oVar);
        A = new o("35", oVar);
        B = new o("36", oVar);
        C = new o("37", oVar);
        D = new o("38", oVar);
        E = new o("39", oVar);
        F = l81.A;
        G = l81.G;
        o oVar2 = new o("1.3.132.1");
        H = new o("11.0", oVar2);
        I = new o("11.1", oVar2);
        J = new o("11.2", oVar2);
        K = new o("11.3", oVar2);
        L = new o("14.0", oVar2);
        M = new o("14.1", oVar2);
        N = new o("14.2", oVar2);
        O = new o("14.3", oVar2);
        P = new o("15.0", oVar2);
        Q = new o("15.1", oVar2);
        R = new o("15.2", oVar2);
        S = new o("15.3", oVar2);
        yg.d(oVar2, "16.0", "16.1", "16.2", "16.3");
    }
}